<?php
// Set doctype explicitly if it is not `HTML4_LOOSE`, i.e. 'HTML 4.01 Transitional'
$this->doctype('HTML5');

// Load translation data
$this->i18nTheme();

//HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
$this->js(array(
    pi::url('static/js/html5shiv.js') => array(
        'conditional' => 'lt IE 9'
    ),
    pi::url('static/js/respond.min.js') => array(
        'conditional' => 'lt IE 9'
    ),
));

// Load jQuery
$this->jquery();

// Load Bootstrap css/js and font-awesome
$this->bootstrap(array(
    'js/bootstrap.min.js',
    'font-awesome/css/font-awesome.min.css'
));

// Load front.css
$this->css($this->assetTheme('css/front.css'));

// Load localization css
$this->css($this->assetLocale('locale.css'));

// Load front.js on footer
$this->footScript()->appendFile($this->assetTheme('js/front.js'));

// Apple icons
// Apple icon for iphone
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'href'  => $this->assetTheme('image/touch-icon-iphone.png')
));
// Apple icon for ipad
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '72x72',
    'href'  => $this->assetTheme('image/touch-icon-ipad.png')
));
// Apple icon for iphone retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-iphone-retina.png')
));
// Apple icon for ipad retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-ipad-retina.png')
));

// Meta Viewport Tag
$this->headMeta('width=device-width, initial-scale=1.0', 'viewport');

// Explicitly load favicon
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'type'  => 'image/x-icon',
    'href'  => $this->favicon(),
));
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'type'  => 'image/png',
    'href'  => $this->favicon('favicon.png'),
));

// Load google analytics code
$this->ga();

// Get module name
$module = Pi::service('module')->current();

// Get navigation
$navigation = $this->nav('front');

// Get block
$blocks = $this->blocks();
$blockTemplate = $this->template('block');

// Get breadcrumbs
$breadcrumbs = $this->breadcrumb(
    array('prefix' => array(
        array(
            'label' => __('Home'),
            'href' => Pi::url($this->url('home'))
        )
    ))
);

// Check page
if ($module == 'page') {
    $d = (array) Pi::service('url')->getRouteMatch();
    foreach ($d as $value) {
        $a[] = $value;
    }
    if ($a[1]['id'] == 13) {
        Pi::service('i18n')->setLocale('en');
        $locale = 'en';
        $sitename = 'Shiva Moghanloo';
    }
}
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="<?php echo $charset; ?>">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans" rel="stylesheet">
</head>
<body id="pi-<?php echo $module; ?>" class="pi-locale-<?php echo $locale; ?> pi-front">
<!-- Header: brand, slogan, user bar -->
<div class="container">
    <div class="row">
        <?php if ($locale == 'en') { ?>
            <header class="pi-header clearfix">
                <div class="col-md-6">
                    <div class="pi-header-cover">
                        <!-- <img class="img-responsive" src="<?php echo $this->assetTheme('image/header-cover.jpg'); ?>" alt="<?php echo _escape($sitename); ?>"> -->
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="pi-header-menu">
                        <ul>
                            <li class="pi-header-menu-1"><a href="<?php echo Pi::url($this->url('home')); ?>blog" title="Blog">Blog</a></li>
                            <li class="pi-header-menu-2"><a href="<?php echo Pi::url($this->url('home')); ?>news/my-books" title="My books">My books</a></li>
                            <li class="pi-header-menu-3"><a href="<?php echo Pi::url($this->url('home')); ?>news/articles" title="Articles">Articles</a></li>
                            <li class="pi-header-menu-4"><a href="<?php echo Pi::url($this->url('home')); ?>news/speeches-meetings-panel-discussion" title="Speeches, meetings, panel discussion">Speeches, meetings</a></li>
                            <li class="pi-header-menu-5"><a href="<?php echo Pi::url($this->url('home')); ?>news/workshops-awards-contests" title="Workshops, awards contests">Workshops, awards</a></li>
                            <li class="pi-header-menu-6"><a href="<?php echo Pi::url($this->url('home')); ?>news/photo-video-audio-gallery" title="Photo, video, audio gallery">Gallery</a></li>
                            <li class="pi-header-menu-7"><a href="<?php echo Pi::url($this->url('home')); ?>guestbook" title="Guest book">Guest book</a></li>
                            <li class="pi-header-menu-8"><a href="<?php echo Pi::url($this->url('home')); ?>page/about-me" title="About me">About me</a></li>
                            <li class="pi-header-menu-9"><a href="<?php echo Pi::url($this->url('home')); ?>contact" title="Contact me">Contact me</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="pi-header-language">
                        <ul class="list-inline">
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>">فارسی</a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>page/en">English</a></li>
                        </ul>
                    </div>
                    <div class="pi-header-name">
                        <?php if ($module == 'system') { ?>
                            <h1>
                                <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>">
                                    <?php echo _escape($sitename); ?>
                                </a>
                            </h1>
                        <?php } else { ?>
                            <h2>
                                <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>">
                                    <?php echo _escape($sitename); ?>
                                </a>
                            </h2>
                        <?php } ?>
                    </div>
                </div>
            </header>
        <?php } else { ?>
            <header class="pi-header clearfix">
                <div class="col-md-3">
                    <div class="pi-header-language">
                        <ul class="list-inline">
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>">فارسی</a></li>
                            <li><a href="<?php echo Pi::url($this->url('home')); ?>page/en">English</a></li>
                        </ul>
                    </div>
                    <div class="pi-header-name">
                        <?php if ($module == 'system') { ?>
                            <h1>
                                <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>">
                                    <?php echo _escape($sitename); ?>
                                </a>
                            </h1>
                        <?php } else { ?>
                            <h2>
                                <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>">
                                    <?php echo _escape($sitename); ?>
                                </a>
                            </h2>
                        <?php } ?>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="pi-header-menu">
                        <ul>
                            <li class="pi-header-menu-1"><a href="<?php echo Pi::url($this->url('home')); ?>blog" title="اخبار">اخبار</a></li>
                            <li class="pi-header-menu-2"><a href="<?php echo Pi::url($this->url('home')); ?>news/my-books" title="کتاب های من">کتاب های من</a></li>
                            <li class="pi-header-menu-3"><a href="<?php echo Pi::url($this->url('home')); ?>news/articles" title="مقالات">مقالات</a></li>
                            <li class="pi-header-menu-4"><a href="<?php echo Pi::url($this->url('home')); ?>news/speeches-meetings-panel-discussion" title="سخنرانی, میزگرد و گفتگو">سخنرانی, میزگرد و گفتگو</a></li>
                            <li class="pi-header-menu-5"><a href="<?php echo Pi::url($this->url('home')); ?>news/workshops-awards-contests" title="داوری ها, کارگاه ها و جوایز">داوری ها, کارگاه ها و جوایز</a></li>
                            <li class="pi-header-menu-6"><a href="<?php echo Pi::url($this->url('home')); ?>news/photo-video-audio-gallery" title="گالری عکس و صوت و ویدیو">گالری عکس و صوت و ویدیو</a></li>
                            <li class="pi-header-menu-7"><a href="<?php echo Pi::url($this->url('home')); ?>guestbook" title="دفتر مهمان">دفتر مهمان</a></li>
                            <li class="pi-header-menu-8"><a href="<?php echo Pi::url($this->url('home')); ?>page/about-me" title="درباره من">درباره من</a></li>
                            <li class="pi-header-menu-9"><a href="<?php echo Pi::url($this->url('home')); ?>contact" title="تماس با من">تماس با من</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="pi-header-cover">
                        <!-- <img class="img-responsive" src="<?php echo $this->assetTheme('image/header-cover.jpg'); ?>" alt="<?php echo _escape($sitename); ?>"> -->
                    </div>
                </div>
            </header>
        <?php } ?>
        <!-- Page main content: breadcrumb, flash-messenger, blocks and module content -->
        <section class="pi-section">
            <?php if ($breadcrumbs) { echo $breadcrumbs; } ?>
            <div class="pi-main-container">

                <!-- Flash messenger -->
                <?php include $this->template('flash-messenger'); ?>
                <!-- Top head zone -->
                <?php if (!empty($blocks['0'])) { ?>
                    <div class="pi-zone-0">
                        <?php foreach ($blocks['0'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
                <div class="clearfix">
                    <!-- Left zone -->
                    <?php if (!empty($blocks['1'])) { ?>
                        <div class="pi-zone-1 col-md-3">
                            <?php foreach ($blocks['1'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                    <div class="<?php
                    if (isset($blocks['1']) && isset($blocks['8'])) {
                        echo 'col-md-6';
                    } elseif (isset($blocks['1']) || isset($blocks['8'])) {
                        echo 'col-md-9';
                    } else {
                        echo 'col-md-12';
                    }
                    ?>">
                        <!-- Center top zone -->
                        <?php if (isset($blocks['2'])) { ?>
                            <div class="pi-zone-2">
                                <?php foreach ($blocks['2'] as $block) {
                                    include $blockTemplate;
                                } ?>
                            </div>
                        <?php } ?>
                        <?php if (isset($blocks['3']) || isset($blocks['4'])) { ?>
                            <div class="row">
                                <div class="col-md-6 pi-zone-3">
                                    <?php
                                    if (isset($blocks['3'])) {
                                        foreach ($blocks['3'] as $block) {
                                            include $blockTemplate;
                                        }
                                    }
                                    ?>
                                </div>
                                <div class="col-md-6 pi-zone-4">
                                    <?php
                                    if (isset($blocks['4'])) {
                                        foreach ($blocks['4'] as $block) {
                                            include $blockTemplate;
                                        }
                                    }
                                    ?>
                                </div>
                            </div>
                        <?php } ?>
                        <!-- Module content starts -->
                        <?php if (!empty($content)) { ?>
                            <div class="<?php echo $module; ?>">
                                <div class="pi-module-content" ng-app="<?php echo $module; ?>">
                                    <?php echo $content; ?>
                                </div>
                                <?php echo Pi::service('comment')->load(array('options' => array('type' => 'js'))); ?>
                            </div>
                        <?php } ?>
                        <!-- Module content ends -->
                        <?php if (isset($blocks['5']) || isset($blocks['6'])) { ?>
                            <div class="row">
                                <div class="col-md-6 pi-zone-5">
                                    <?php
                                    if (isset($blocks['5'])) {
                                        foreach ($blocks['5'] as $block) {
                                            include $blockTemplate;
                                        }
                                    }
                                    ?>
                                </div>
                                <div class="col-md-6 pi-zone-6">
                                    <?php
                                    if (isset($blocks['6'])) {
                                        foreach ($blocks['6'] as $block) {
                                            include $blockTemplate;
                                        }
                                    }
                                    ?>
                                </div>
                            </div>
                        <?php } ?>
                        <!-- Center bottom zone -->
                        <?php if (isset($blocks['7'])) { ?>
                            <div class="pi-zone-7">
                                <?php foreach ($blocks['7'] as $block) {
                                    include $blockTemplate;
                                } ?>
                            </div>
                        <?php } ?>
                    </div>
                    <!-- Right zone -->
                    <?php if (isset($blocks['8'])) { ?>
                        <div class="col-md-3 pi-zone-8">
                            <?php foreach ($blocks['8'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                </div>
                <!-- Bottom foot zone -->
                <?php if (isset($blocks['99'])) { ?>
                    <div class="pi-zone-99">
                        <?php foreach ($blocks['99'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
            </div>

        </section>
        <!-- Footer: sitelink -->
        <footer class="pi-footer clearfix">
            <div class="text-left col-md-5" data-rel="license">تمام حقوق مطالب برای وب سایت <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>"><?php echo _escape($sitename); ?></a> محفوظ است.</div>
            <div class="text-center col-md-2">
                <ul class="list-inline">
                    <li><a target="_blank" href="https://www.instagram.com/shiva_moghanloo" title="Shiva Moghanloo on instagram"><i class="fa fa-instagram"></i></a></li>
                    <li><a target="_blank" href="https://fa.wikipedia.org/wiki/شیوا_مقانلو" title="Shiva Moghanloo on wikipedia"><i class="fa fa-wikipedia-w"></i></a></li>
                    <li><a target="_blank" href="https://www.facebook.com/shiva.moghanloo" title="Shiva Moghanloo on facebook"><i class="fa fa-facebook"></i></a></li>
                </ul>
            </div>
            <div class="text-right col-md-5" data-rel="license">طراحی و توسعه <a title="فراگسترش" href="http://www.faragostaresh.com" target="_blank">فراگسترش</a></div>
        </footer>
    </div>
</div>
</body>
</html>